global using DevExpress.Blazor;
global using Mapster;
global using Blazored.Toast;
global using Blazored.Toast.Services;
global using Blazored.LocalStorage;
global using McDermott.Domain.Entities;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Data.SqlClient;
global using Microsoft.JSInterop;
global using Newtonsoft.Json;
global using System.Reflection;
global using System.Security.Cryptography;
global using System.Text;
global using McDermott.Web.Components.Layout;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.CodeAnalysis;
global using System.Globalization;
global using Microsoft.AspNetCore.SignalR.Client;
global using static McDermott.Application.Extentions.EnumHelper;

global using McDermott.Web.Extentions;

global using McDermott.Application.Dtos.Bpjs;
global using McDermott.Application.Dtos.Config;
global using McDermott.Application.Dtos.Medical;
global using McDermott.Application.Dtos.Transaction;
global using McDermott.Application.Dtos.Employee;
global using McDermott.Application.Dtos.Patient;
global using McDermott.Application.Dtos.Pharmacy;
global using McDermott.Application.Dtos.Inventory;
global using McDermott.Application.Dtos.BpjsIntegration;
global using McDermott.Application.Dtos;

global using DevExpress.Data.XtraReports.Native;

global using OfficeOpenXml;

global using static McDermott.Application.Features.Commands.Medical.CronisCategoryCommand;
global using static McDermott.Application.Features.Commands.Inventory.InventoryAdjusmentCommand;
global using static McDermott.Application.Features.Commands.Inventory.InventoryAdjusmentDetailCommand;
global using static McDermott.Application.Features.Commands.Medical.DoctorScheduleSlotCommand;
global using static McDermott.Application.Features.Commands.BpjsIntegration.AllergyCommand;
global using static McDermott.Application.Features.Commands.BpjsIntegration.AwarenessCommand;
global using static McDermott.Application.Features.Commands.Bpjs.SystemParameterCommand;
global using static McDermott.Application.Features.Commands.Inventory.ProductCommand;
global using static McDermott.Application.Features.Commands.Medical.LabTestCommand;
global using static McDermott.Application.Features.Commands.Transaction.GeneralConsultanClinicalAssesmentCommand;
global using static McDermott.Application.Features.Commands.Bpjs.BpjsClassificationCommand;
global using static McDermott.Application.Features.Commands.Medical.BuildingLocationCommand;
global using static McDermott.Application.Features.Commands.Pharmacy.ReorderingRuleCommand;
global using static McDermott.Application.Features.Commands.Inventory.ProductCategoryCommand;
global using static McDermott.Application.Features.Commands.Inventory.UomCommand;
global using static McDermott.Application.Features.Commands.Inventory.UomCategoryCommand;
global using static McDermott.Application.Features.Commands.Pharmacy.ActiveComponentCommand;
global using static McDermott.Application.Features.Commands.Pharmacy.DrugDosageCommand;
global using static McDermott.Application.Features.Commands.Pharmacy.DrugRouteCommand;
global using static McDermott.Application.Features.Commands.Transaction.LabResultDetailCommand;
global using static McDermott.Application.Features.Commands.Medical.LabTestDetailCommand;
global using static McDermott.Application.Features.Commands.Medical.SampleTypeCommand;
global using static McDermott.Application.Features.Commands.Medical.LabUomCommand;
global using static McDermott.Application.Features.Commands.Patient.ClassTypeCommand;
global using static McDermott.Application.Features.Commands.Medical.LocationCommand;
global using static McDermott.Application.Features.Commands.Medical.ProjectCommand;
global using static McDermott.Application.Features.Commands.Config.CityCommand;
global using static McDermott.Application.Features.Commands.Employee.DepartmentCommand;
global using static McDermott.Application.Features.Commands.Config.DistrictCommand;
global using static McDermott.Application.Features.Commands.Employee.JobPositionCommand;
global using static McDermott.Application.Features.Commands.Config.ProvinceCommand;
global using static McDermott.Application.Features.Commands.Config.ReligionCommand;
global using static McDermott.Application.Features.Commands.Config.UserCommand;
global using static McDermott.Application.Features.Commands.Config.VillageCommand;
global using static McDermott.Application.Features.Commands.Config.GroupCommand;
global using static McDermott.Application.Features.Commands.Medical.BuildingCommand;
global using static McDermott.Application.Features.Commands.Medical.DoctorScheduleCommand;
global using static McDermott.Application.Features.Commands.Transaction.GeneralConsultanServiceCommand;
global using static McDermott.Application.Features.Commands.Queue.KioskCommand;
global using static McDermott.Application.Features.Commands.Medical.InsuranceCommand;
global using static McDermott.Application.Features.Commands.Medical.ServiceCommand;
global using static McDermott.Application.Features.Commands.Config.CountryCommand;
global using static McDermott.Application.Features.Commands.Config.MenuCommand;
global using static McDermott.Application.Features.Commands.Medical.HealthCenterCommand;
global using static McDermott.Application.Features.Commands.Medical.SpecialityCommand;
global using static McDermott.Application.Features.Commands.Config.CompanyCommand;
global using static McDermott.Application.Features.Commands.Patient.FamilyRelationCommand;
global using static McDermott.Application.Features.Commands.Patient.PatientFamilyRelationCommand;
global using static McDermott.Application.Features.Commands.Patient.InsurancePolicyCommand;
global using static McDermott.Application.Features.Commands.Medical.DiagnosisCommand;
global using static McDermott.Application.Features.Commands.Medical.DiseaseCategoryCommand;
global using static McDermott.Application.Features.Commands.Medical.NursingDiagnosesCommand;
global using static McDermott.Application.Features.Commands.Config.GroupMenuCommand;
global using static McDermott.Application.Features.Commands.Transaction.GeneralConsultanCPPTCommand;
global using static McDermott.Application.Features.Commands.Transaction.GeneralConsultanMedicalSupportCommand;
global using static McDermott.Application.Features.Commands.Patient.PatientAllergyCommand;
global using static McDermott.Application.Features.Commands.Medical.DoctorScheduledCommand;
global using static McDermott.Application.Features.Commands.Medical.DoctorScheduleDetailCommand;