global using DevExpress.Blazor;
global using Mapster;
global using McHealthCare.Application.Dtos.Configuration;
global using McHealthCare.Application.Dtos.Others;
global using Microsoft.AspNetCore.Components.Forms;
global using OfficeOpenXml;
global using McHealthCare.Web.Extentions.CS;
global using Serilog;
global using Microsoft.AspNetCore.Components;

global using static McHealthCare.Application.Features.CommandsQueries.Configuration.JobPositionCommand;
global using McHealthCare.Domain.Entities.Configuration;
global using static McHealthCare.Application.Features.CommandsQueries.Employees.DepartmentCommand;
global using McHealthCare.Domain.Entities;
global using static McHealthCare.Extentions.EnumHelper;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.EmailSettingCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.CountryCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.ProvinceCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.GroupCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.GroupMenuCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.MenuCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.CityCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.DistrictCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.CompanyCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.ReligionCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.VillageCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Inventory.UomCategoryCommand;
global using McHealthCare.Application.Dtos.Inventory;
global using McHealthCare.Application.Dtos.Transaction; 
global using OfficeOpenXml.Style;
global using Microsoft.JSInterop;
global using McHealthCare.Application.Dtos.Medical;
global using McHealthCare.Domain.Entities.Products;
global using DevExpress.Data.XtraReports.Native;
global using McHealthCare.Application.Dtos.BpjsIntegration;
global using static McHealthCare.Application.Features.CommandsQueries.Bpjs.AllergyCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.InventoryAdjusmentCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.InventoryAdjusmentDetailCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.ProductCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.ProductCategoryCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.UomCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.StockProductCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.TransactionStockCommand;
global using static McHealthCare.Application.Features.Commands.ClinicServices.GeneralConsultanServiceCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.ReceivingCommand;
global using static McHealthCare.Application.Features.Commands.Inventory.TransferStockCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Inventory.LocationCommand;
global using McHealthCare.Application.Dtos.Bpjs;
global using Newtonsoft.Json;
global using System.Text.Json.Serialization; 
global using McHealthCare.Application.Dtos.Pharmacies;
global using System.Globalization;
global using static McHealthCare.Application.Features.Commands.Bpjs.BpjsClassificationCommand;
 

global using static McHealthCare.Application.Features.Commands.Pharmacies.ActiveComponentCommand;
global using static McHealthCare.Application.Features.Commands.Pharmacies.DrugDosageCommand;
global using static McHealthCare.Application.Features.Commands.Pharmacies.DrugRouteCommand;
global using static McHealthCare.Application.Features.Commands.Pharmacies.FormDrugCommand;
global using static McHealthCare.Application.Features.Commands.Pharmacies.MedicamentCommand;