global using DevExpress.Blazor;
global using Mapster;
global using McHealthCare.Application.Dtos.Configuration;
global using McHealthCare.Application.Dtos.Others;
global using Microsoft.AspNetCore.Components.Forms;
global using OfficeOpenXml;
global using McHealthCare.Web.Extentions.CS;
global using Serilog;
global using Microsoft.AspNetCore.Components;

global using static McHealthCare.Application.Features.CommandsQueries.Configuration.JobPositionCommand;
global using McHealthCare.Domain.Entities.Configuration;
global using static McHealthCare.Application.Features.CommandsQueries.Employees.DepartmentCommand;
global using McHealthCare.Domain.Entities;
global using static McHealthCare.Extentions.EnumHelper;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.EmailSettingCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.CountryCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.ProvinceCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.GroupCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.GroupMenuCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.MenuCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.CityCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.DistrictCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.CompanyCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.ReligionCommand;
global using static McHealthCare.Application.Features.CommandsQueries.Configuration.VillageCommand;